#!/bin/sh

elif [ "x$1" = "xpkg" ]; then
        set -e

        export USER_UID=${USER_UID}

        ssh-keyscan -t rsa github.com >> /etc/ssh/ssh_known_hosts
        git config --global url."ssh://git@github.com/".insteadOf "https://github.com/"

        git clone ssh://git@github.com/vpngen/keydesk-web

        keydesk-web/debpkg/src/build.sh

        exit 0
fi

docker run --rm  -v $(readlink -f $SSH_AUTH_SOCK):/ssh-agent -e SSH_AUTH_SOCK=/ssh-agent -e AUTH_KEY="${AUTH_KEY}" -e USER_UID=$(id -u) -v ${PWD}:/data node:18-buster /data/build pkg

