# docker build  -t test_admin-panel:latest -f Dockerfile .
# docker-compose -f compose/local.yml up -d
version: '3.9'
services:
  frontend:
    container_name: admin-panel
    image: test_admin-panel:latest
    restart: always
    ports:
      - 8082:8080
    healthcheck:
      test: ["CMD-SHELL", "wget -O /dev/null http://localhost:8080 || exit 1"]
      interval: 1m
      timeout: 3s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
