version: '3.9'
services:
  admin-panel:
    container_name: admin-panel
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    ports:
      - 8082:8080
    healthcheck:
      test: ["CMD-SHELL", "wget -O /dev/null http://localhost:8080 || exit 1"]
      interval: 1m
      timeout: 3s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
